language: python
sudo: required
dist: xenial
python: "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pipenv
  - pipenv sync
# command to run tests
script:
  - flake8 app --statistics --count
  - pipenv run pytest
